import {
  GOOGLE_MAPS_API_KEY_MOBILE,
  SUPABASE_URL,
  SUPABASE_API_KEY,
  ANDROID_CLIENT_ID,
  IOS_CLIENT_ID,
  EXPO_CLIENT_ID,
  FACEBOOK_APP_ID
} from "@env";

export default {
  GOOGLE_MAPS_API_KEY_MOBILE,
  SUPABASE_API_KEY,
  SUPABASE_URL,
  ANDROID_CLIENT_ID,
  IOS_CLIENT_ID,
  EXPO_CLIENT_ID,
  FACEBOOK_APP_ID
};
